# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11KttAKVkFiZGv9xDzrL2Vsx-CPMQewIH
"""

import streamlit as st
import torch
from transformers import AutoTokenizer, AutoModelForSequenceClassification
from transformers import AutoModelForCausalLM, AutoTokenizer
from collections import deque
import numpy as np

st.set_page_config(page_title="🧠 Human Companion", layout="wide")

# Load Emotion Detection Model
@st.cache_resource
def load_emotion_model():
    model = AutoModelForSequenceClassification.from_pretrained("final_emotion_model")
    tokenizer = AutoTokenizer.from_pretrained("final_emotion_model")
    return model, tokenizer

model, tokenizer = load_emotion_model()

label_map = {
    0: 'admiration', 1: 'amusement', 2: 'anger', 3: 'annoyance', 4: 'approval',
    5: 'caring', 6: 'confusion', 7: 'curiosity', 8: 'desire', 9: 'disappointment',
    10: 'disapproval', 11: 'embarrassment', 12: 'excitement', 13: 'fear',
    14: 'gratitude', 15: 'grief', 16: 'joy', 17: 'love', 18: 'nervousness',
    19: 'optimism', 20: 'pride', 21: 'realization', 22: 'relief', 23: 'remorse',
    24: 'sadness', 25: 'surprise', 26: 'neutral', 27: 'burnout', 28: 'anxiety'
}

# Emotion Detection
def detect_emotion(text):
    inputs = tokenizer(text, return_tensors="pt", truncation=True)
    with torch.no_grad():
        outputs = model(**inputs)
    probs = torch.nn.functional.softmax(outputs.logits, dim=1)[0]
    top_probs, top_labels = torch.topk(probs, 5)
    results = [(label_map[int(label)], float(prob)) for label, prob in zip(top_labels, top_probs)]
    return results

@st.cache_resource
def load_chat_model():
    model_name = "microsoft/DialoGPT-medium"
    tokenizer = AutoTokenizer.from_pretrained(model_name)
    model = AutoModelForCausalLM.from_pretrained(model_name)
    return model, tokenizer

chat_model, chat_tokenizer = load_chat_model()

def generate_response(chat_history, user_input):
    new_user_input_ids = chat_tokenizer.encode(user_input + chat_tokenizer.eos_token, return_tensors='pt')
    bot_input_ids = new_user_input_ids if chat_history is None else torch.cat([chat_history, new_user_input_ids], dim=-1)
    chat_history = bot_input_ids

    with torch.no_grad():
        output_ids = chat_model.generate(
            bot_input_ids,
            max_length=1000,
            pad_token_id=chat_tokenizer.eos_token_id,
            do_sample=True,
            top_k=50,
            top_p=0.95,
            temperature=0.75
        )

    response = chat_tokenizer.decode(output_ids[:, bot_input_ids.shape[-1]:][0], skip_special_tokens=True)
    return response, chat_history

# --- Chat Renderer ---
def render_message(sender, message):
    if sender == "user":
        st.markdown(f"""
        <div style="display: flex; justify-content: flex-end; margin: 10px;">
            <div style="background-color: #d4fdd6; color: black; padding: 10px 15px;
                        border-radius: 18px 0px 18px 18px; max-width: 70%; position: relative;
                        font-size: 16px; font-family: 'Segoe UI', sans-serif;">
                {message}
                <div style="position: absolute; right: -10px; top: 12px;
                            width: 0; height: 0; border-top: 10px solid transparent;
                            border-left: 10px solid #d4fdd6; border-bottom: 10px solid transparent;">
                </div>
            </div>
        </div>
        """, unsafe_allow_html=True)
    else:
        st.markdown(f"""
        <div style="display: flex; justify-content: flex-start; margin: 10px;">
            <div style="background-color: #d0eaff; color: black; padding: 10px 15px;
                        border-radius: 0px 18px 18px 18px; max-width: 70%; position: relative;
                        font-size: 16px; font-family: 'Segoe UI', sans-serif;">
                {message}
                <div style="position: absolute; left: -10px; top: 12px;
                            width: 0; height: 0; border-top: 10px solid transparent;
                            border-right: 10px solid #d0eaff; border-bottom: 10px solid transparent;">
                </div>
            </div>
        </div>
        """, unsafe_allow_html=True)

# --- Sidebar ---
with st.sidebar:
    st.markdown("### 🥽 Need Help?")
    st.button("🎯 Career Help")
    st.button("🧹 Daily Routine Help")
    st.button("🛒 Grocery Help")
    st.button("🍔 Food Ordering")
    st.button("🚨 Panic Button")

# --- Main App ---
st.markdown("## 💬 Check Your Emotion")
user_text = st.text_input("Enter text to detect your emotions:")

if st.button("Analyze Emotion"):
    if user_text:
        emotions = detect_emotion(user_text)
        st.markdown("#### Detected Emotions:")
        for emotion, score in emotions:
            st.write(f"**{emotion.capitalize()}**: {score:.2f}")

if st.button("🌿 Take a Deep Breath"):
    st.success("Inhale deeply... hold... exhale. You're doing great. 🌬️")

# --- Chat Interface ---
st.markdown("## 👤 Chat with your Companion")
chat_input = st.text_input("🗣️ Type your message like you're chatting with a friend", key="chat_input")

if "chat_history" not in st.session_state:
    st.session_state.chat_history = deque(maxlen=20)

if "chat_token_history" not in st.session_state:
    st.session_state.chat_token_history = None

if chat_input:
    st.session_state.chat_history.append(("user", chat_input))
    response, updated_history = generate_response(st.session_state.chat_token_history, chat_input)
    st.session_state.chat_token_history = updated_history
    st.session_state.chat_history.append(("ai", response))

for sender, msg in list(st.session_state.chat_history):
    render_message(sender, msg)